name: roles
version: 1.0.1.4
author: Philipp Chrszon
maintainer: philipp.chrszon@tu-dresden.de
copyright: ! 'Copyright: (c) 2019 Philipp Chrszon'
license: BSD3
synopsis: Modeling and analysis of role-based systems
description:
  This tool provides a language for modeling the operational behavior of
  role-based systems. A model can then be analyzed by translating it to the
  input language of the probabilistic model checker PRISM.

category: Language

dependencies:
  - base >=4.7 && <5
  - array
  - constraints
  - containers
  - directory
  - filepath
  - gitrev
  - lang-prism
  - lens
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - prettyprinter
  - prettyprinter-ansi-terminal
  - process
  - random
  - text
  - uuid

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  rbsc:
    source-dirs: app
    main: Main.hs
    dependencies:
      - roles

tests:
  lang-prism-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - roles
      - hspec
      - QuickCheck
      - syb
      - template-haskell
